#!/usr/bin/env bash

checkId () {
    if [ $(id -u) == 0 ]; then
        echo
        echo "Do not run this script as root."
        echo
    fi
}

help () {
    echo "help function"
}

version () {
    echo "version function"
}

main () {
    checkId
    while [[ "$#" -gt 0 ]]; do
        case $1 in
        -h|--help)
            help
            ;;
        -v|--version)
            version
            ;;
        *)
            echo "Unknown option: $1" >&2
            ;;
        esac
        shift
    done
}

main "$@"
