#!/usr/bin/env bash

checkId () {
    if [ $(id -u) == 0 ]; then
        echo
        echo "Do not run this script as root."
        echo
    fi
}


help () {
    echo "Usage: clear-history [options]"
    echo ""
    echo "Options:"
    echo "    -h, --help                  Display this help message."
    echo "    -v, --version               Display version information."
    echo ""
    echo "Example:"
    echo "    $ clear-history"
}


version () {
    echo "clear-history Version 1.0"
    echo "Licensed under the terms of the GNU General Public License."
}


clearAll () {
    ls -a ~/ | grep history | while read line; do cat /dev/null > $line; done
}


main () {
    checkId
    while [[ "$#" -gt 0 ]]; do
        case $1 in
        -h|--help)
            help
            ;;
        -v|--version)
            version
            ;;
        *)
            echo "Unknown option: $1" >&2
            ;;
        esac
        shift
    done
    clearAll
}


main "$@"
